[[MPark_Variant]]
arch = "aarch64"
git-tree-sha1 = "e08914e1c6da12dd18b5ce48464688e83321491d"
os = "macos"

    [[MPark_Variant.download]]
    sha256 = "1a4d942b8b2314d19ca54ab7341be1af621198fe7feb30d2016b04da879f0301"
    url = "https://github.com/JuliaBinaryWrappers/MPark_Variant_jll.jl/releases/download/MPark_Variant-v1.4.0+1/MPark_Variant.v1.4.0.aarch64-apple-darwin.tar.gz"
[[MPark_Variant]]
arch = "aarch64"
git-tree-sha1 = "e08914e1c6da12dd18b5ce48464688e83321491d"
libc = "glibc"
os = "linux"

    [[MPark_Variant.download]]
    sha256 = "1a4d942b8b2314d19ca54ab7341be1af621198fe7feb30d2016b04da879f0301"
    url = "https://github.com/JuliaBinaryWrappers/MPark_Variant_jll.jl/releases/download/MPark_Variant-v1.4.0+1/MPark_Variant.v1.4.0.aarch64-linux-gnu.tar.gz"
[[MPark_Variant]]
arch = "aarch64"
git-tree-sha1 = "e08914e1c6da12dd18b5ce48464688e83321491d"
libc = "musl"
os = "linux"

    [[MPark_Variant.download]]
    sha256 = "1a4d942b8b2314d19ca54ab7341be1af621198fe7feb30d2016b04da879f0301"
    url = "https://github.com/JuliaBinaryWrappers/MPark_Variant_jll.jl/releases/download/MPark_Variant-v1.4.0+1/MPark_Variant.v1.4.0.aarch64-linux-musl.tar.gz"
[[MPark_Variant]]
arch = "aarch64"
git-tree-sha1 = "e08914e1c6da12dd18b5ce48464688e83321491d"
os = "freebsd"

    [[MPark_Variant.download]]
    sha256 = "1a4d942b8b2314d19ca54ab7341be1af621198fe7feb30d2016b04da879f0301"
    url = "https://github.com/JuliaBinaryWrappers/MPark_Variant_jll.jl/releases/download/MPark_Variant-v1.4.0+1/MPark_Variant.v1.4.0.aarch64-unknown-freebsd.tar.gz"
[[MPark_Variant]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "4ead342eca09342d09299de392f58364afbd1a0f"
libc = "glibc"
os = "linux"

    [[MPark_Variant.download]]
    sha256 = "f0d7da935076d340c44915440602a47bc4a7ef993f77bd1497b5486dfcb93dee"
    url = "https://github.com/JuliaBinaryWrappers/MPark_Variant_jll.jl/releases/download/MPark_Variant-v1.4.0+1/MPark_Variant.v1.4.0.armv6l-linux-gnueabihf.tar.gz"
[[MPark_Variant]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "4ead342eca09342d09299de392f58364afbd1a0f"
libc = "musl"
os = "linux"

    [[MPark_Variant.download]]
    sha256 = "f0d7da935076d340c44915440602a47bc4a7ef993f77bd1497b5486dfcb93dee"
    url = "https://github.com/JuliaBinaryWrappers/MPark_Variant_jll.jl/releases/download/MPark_Variant-v1.4.0+1/MPark_Variant.v1.4.0.armv6l-linux-musleabihf.tar.gz"
[[MPark_Variant]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "4ead342eca09342d09299de392f58364afbd1a0f"
libc = "glibc"
os = "linux"

    [[MPark_Variant.download]]
    sha256 = "f0d7da935076d340c44915440602a47bc4a7ef993f77bd1497b5486dfcb93dee"
    url = "https://github.com/JuliaBinaryWrappers/MPark_Variant_jll.jl/releases/download/MPark_Variant-v1.4.0+1/MPark_Variant.v1.4.0.armv7l-linux-gnueabihf.tar.gz"
[[MPark_Variant]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "4ead342eca09342d09299de392f58364afbd1a0f"
libc = "musl"
os = "linux"

    [[MPark_Variant.download]]
    sha256 = "f0d7da935076d340c44915440602a47bc4a7ef993f77bd1497b5486dfcb93dee"
    url = "https://github.com/JuliaBinaryWrappers/MPark_Variant_jll.jl/releases/download/MPark_Variant-v1.4.0+1/MPark_Variant.v1.4.0.armv7l-linux-musleabihf.tar.gz"
[[MPark_Variant]]
arch = "i686"
git-tree-sha1 = "4ead342eca09342d09299de392f58364afbd1a0f"
libc = "glibc"
os = "linux"

    [[MPark_Variant.download]]
    sha256 = "f0d7da935076d340c44915440602a47bc4a7ef993f77bd1497b5486dfcb93dee"
    url = "https://github.com/JuliaBinaryWrappers/MPark_Variant_jll.jl/releases/download/MPark_Variant-v1.4.0+1/MPark_Variant.v1.4.0.i686-linux-gnu.tar.gz"
[[MPark_Variant]]
arch = "i686"
git-tree-sha1 = "4ead342eca09342d09299de392f58364afbd1a0f"
libc = "musl"
os = "linux"

    [[MPark_Variant.download]]
    sha256 = "f0d7da935076d340c44915440602a47bc4a7ef993f77bd1497b5486dfcb93dee"
    url = "https://github.com/JuliaBinaryWrappers/MPark_Variant_jll.jl/releases/download/MPark_Variant-v1.4.0+1/MPark_Variant.v1.4.0.i686-linux-musl.tar.gz"
[[MPark_Variant]]
arch = "i686"
git-tree-sha1 = "4ead342eca09342d09299de392f58364afbd1a0f"
os = "windows"

    [[MPark_Variant.download]]
    sha256 = "f0d7da935076d340c44915440602a47bc4a7ef993f77bd1497b5486dfcb93dee"
    url = "https://github.com/JuliaBinaryWrappers/MPark_Variant_jll.jl/releases/download/MPark_Variant-v1.4.0+1/MPark_Variant.v1.4.0.i686-w64-mingw32.tar.gz"
[[MPark_Variant]]
arch = "powerpc64le"
git-tree-sha1 = "e08914e1c6da12dd18b5ce48464688e83321491d"
libc = "glibc"
os = "linux"

    [[MPark_Variant.download]]
    sha256 = "1a4d942b8b2314d19ca54ab7341be1af621198fe7feb30d2016b04da879f0301"
    url = "https://github.com/JuliaBinaryWrappers/MPark_Variant_jll.jl/releases/download/MPark_Variant-v1.4.0+1/MPark_Variant.v1.4.0.powerpc64le-linux-gnu.tar.gz"
[[MPark_Variant]]
arch = "riscv64"
git-tree-sha1 = "e08914e1c6da12dd18b5ce48464688e83321491d"
libc = "glibc"
os = "linux"

    [[MPark_Variant.download]]
    sha256 = "1a4d942b8b2314d19ca54ab7341be1af621198fe7feb30d2016b04da879f0301"
    url = "https://github.com/JuliaBinaryWrappers/MPark_Variant_jll.jl/releases/download/MPark_Variant-v1.4.0+1/MPark_Variant.v1.4.0.riscv64-linux-gnu.tar.gz"
[[MPark_Variant]]
arch = "x86_64"
git-tree-sha1 = "e08914e1c6da12dd18b5ce48464688e83321491d"
os = "macos"

    [[MPark_Variant.download]]
    sha256 = "1a4d942b8b2314d19ca54ab7341be1af621198fe7feb30d2016b04da879f0301"
    url = "https://github.com/JuliaBinaryWrappers/MPark_Variant_jll.jl/releases/download/MPark_Variant-v1.4.0+1/MPark_Variant.v1.4.0.x86_64-apple-darwin.tar.gz"
[[MPark_Variant]]
arch = "x86_64"
git-tree-sha1 = "e08914e1c6da12dd18b5ce48464688e83321491d"
libc = "glibc"
os = "linux"

    [[MPark_Variant.download]]
    sha256 = "1a4d942b8b2314d19ca54ab7341be1af621198fe7feb30d2016b04da879f0301"
    url = "https://github.com/JuliaBinaryWrappers/MPark_Variant_jll.jl/releases/download/MPark_Variant-v1.4.0+1/MPark_Variant.v1.4.0.x86_64-linux-gnu.tar.gz"
[[MPark_Variant]]
arch = "x86_64"
git-tree-sha1 = "e08914e1c6da12dd18b5ce48464688e83321491d"
libc = "musl"
os = "linux"

    [[MPark_Variant.download]]
    sha256 = "1a4d942b8b2314d19ca54ab7341be1af621198fe7feb30d2016b04da879f0301"
    url = "https://github.com/JuliaBinaryWrappers/MPark_Variant_jll.jl/releases/download/MPark_Variant-v1.4.0+1/MPark_Variant.v1.4.0.x86_64-linux-musl.tar.gz"
[[MPark_Variant]]
arch = "x86_64"
git-tree-sha1 = "e08914e1c6da12dd18b5ce48464688e83321491d"
os = "freebsd"

    [[MPark_Variant.download]]
    sha256 = "1a4d942b8b2314d19ca54ab7341be1af621198fe7feb30d2016b04da879f0301"
    url = "https://github.com/JuliaBinaryWrappers/MPark_Variant_jll.jl/releases/download/MPark_Variant-v1.4.0+1/MPark_Variant.v1.4.0.x86_64-unknown-freebsd.tar.gz"
[[MPark_Variant]]
arch = "x86_64"
git-tree-sha1 = "e08914e1c6da12dd18b5ce48464688e83321491d"
os = "windows"

    [[MPark_Variant.download]]
    sha256 = "1a4d942b8b2314d19ca54ab7341be1af621198fe7feb30d2016b04da879f0301"
    url = "https://github.com/JuliaBinaryWrappers/MPark_Variant_jll.jl/releases/download/MPark_Variant-v1.4.0+1/MPark_Variant.v1.4.0.x86_64-w64-mingw32.tar.gz"
